apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-assistant
  labels:
    app: product-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-assistant
  template:
    metadata:
      labels:
        app: product-assistant
    spec:
      containers:
      - name: product-assistant
        image: 459497895986.dkr.ecr.us-east-1.amazonaws.com/product-assistant:latest
        ports:
        - containerPort: 8000
        env:                                # ✅ Added env section
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: GROQ_API_KEY
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: GOOGLE_API_KEY
        - name: ASTRA_DB_API_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_API_ENDPOINT
        - name: ASTRA_DB_APPLICATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_APPLICATION_TOKEN
        - name: ASTRA_DB_KEYSPACE
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_KEYSPACE